// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udp_msg.discover.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "udp_msg.discover.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace udp_msg {
class discoverDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<discover> {
} _discover_default_instance_;

namespace protobuf_udp_5fmsg_2ediscover_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(discover, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(discover, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(discover, cmd_type_),
  0,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 6, sizeof(discover)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_discover_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "udp_msg.discover.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _discover_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _discover_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\026udp_msg.discover.proto\022\007udp_msg\"\034\n\010dis"
      "cover\022\020\n\010cmd_type\030\001 \002(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 63);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "udp_msg.discover.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_udp_5fmsg_2ediscover_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int discover::kCmdTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

discover::discover()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_udp_5fmsg_2ediscover_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:udp_msg.discover)
}
discover::discover(const discover& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  cmd_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_cmd_type()) {
    cmd_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cmd_type_);
  }
  // @@protoc_insertion_point(copy_constructor:udp_msg.discover)
}

void discover::SharedCtor() {
  _cached_size_ = 0;
  cmd_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

discover::~discover() {
  // @@protoc_insertion_point(destructor:udp_msg.discover)
  SharedDtor();
}

void discover::SharedDtor() {
  cmd_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void discover::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* discover::descriptor() {
  protobuf_udp_5fmsg_2ediscover_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_udp_5fmsg_2ediscover_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const discover& discover::default_instance() {
  protobuf_udp_5fmsg_2ediscover_2eproto::InitDefaults();
  return *internal_default_instance();
}

discover* discover::New(::google::protobuf::Arena* arena) const {
  discover* n = new discover;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void discover::Clear() {
// @@protoc_insertion_point(message_clear_start:udp_msg.discover)
  if (has_cmd_type()) {
    GOOGLE_DCHECK(!cmd_type_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*cmd_type_.UnsafeRawStringPointer())->clear();
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool discover::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:udp_msg.discover)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string cmd_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cmd_type()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cmd_type().data(), this->cmd_type().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "udp_msg.discover.cmd_type");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:udp_msg.discover)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:udp_msg.discover)
  return false;
#undef DO_
}

void discover::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:udp_msg.discover)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string cmd_type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cmd_type().data(), this->cmd_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "udp_msg.discover.cmd_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->cmd_type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:udp_msg.discover)
}

::google::protobuf::uint8* discover::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:udp_msg.discover)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required string cmd_type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cmd_type().data(), this->cmd_type().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "udp_msg.discover.cmd_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->cmd_type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:udp_msg.discover)
  return target;
}

size_t discover::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:udp_msg.discover)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  // required string cmd_type = 1;
  if (has_cmd_type()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cmd_type());
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void discover::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:udp_msg.discover)
  GOOGLE_DCHECK_NE(&from, this);
  const discover* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const discover>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:udp_msg.discover)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:udp_msg.discover)
    MergeFrom(*source);
  }
}

void discover::MergeFrom(const discover& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:udp_msg.discover)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_cmd_type()) {
    set_has_cmd_type();
    cmd_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cmd_type_);
  }
}

void discover::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:udp_msg.discover)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void discover::CopyFrom(const discover& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:udp_msg.discover)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool discover::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;
  return true;
}

void discover::Swap(discover* other) {
  if (other == this) return;
  InternalSwap(other);
}
void discover::InternalSwap(discover* other) {
  cmd_type_.Swap(&other->cmd_type_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata discover::GetMetadata() const {
  protobuf_udp_5fmsg_2ediscover_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_udp_5fmsg_2ediscover_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// discover

// required string cmd_type = 1;
bool discover::has_cmd_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void discover::set_has_cmd_type() {
  _has_bits_[0] |= 0x00000001u;
}
void discover::clear_has_cmd_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void discover::clear_cmd_type() {
  cmd_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cmd_type();
}
const ::std::string& discover::cmd_type() const {
  // @@protoc_insertion_point(field_get:udp_msg.discover.cmd_type)
  return cmd_type_.GetNoArena();
}
void discover::set_cmd_type(const ::std::string& value) {
  set_has_cmd_type();
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:udp_msg.discover.cmd_type)
}
#if LANG_CXX11
void discover::set_cmd_type(::std::string&& value) {
  set_has_cmd_type();
  cmd_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:udp_msg.discover.cmd_type)
}
#endif
void discover::set_cmd_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cmd_type();
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:udp_msg.discover.cmd_type)
}
void discover::set_cmd_type(const char* value, size_t size) {
  set_has_cmd_type();
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:udp_msg.discover.cmd_type)
}
::std::string* discover::mutable_cmd_type() {
  set_has_cmd_type();
  // @@protoc_insertion_point(field_mutable:udp_msg.discover.cmd_type)
  return cmd_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* discover::release_cmd_type() {
  // @@protoc_insertion_point(field_release:udp_msg.discover.cmd_type)
  clear_has_cmd_type();
  return cmd_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void discover::set_allocated_cmd_type(::std::string* cmd_type) {
  if (cmd_type != NULL) {
    set_has_cmd_type();
  } else {
    clear_has_cmd_type();
  }
  cmd_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cmd_type);
  // @@protoc_insertion_point(field_set_allocated:udp_msg.discover.cmd_type)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace udp_msg

// @@protoc_insertion_point(global_scope)
