// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udp_msg.discover.proto

#ifndef PROTOBUF_udp_5fmsg_2ediscover_2eproto__INCLUDED
#define PROTOBUF_udp_5fmsg_2ediscover_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace udp_msg {
class discover;
class discoverDefaultTypeInternal;
extern discoverDefaultTypeInternal _discover_default_instance_;
}  // namespace udp_msg

namespace udp_msg {

namespace protobuf_udp_5fmsg_2ediscover_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_udp_5fmsg_2ediscover_2eproto

// ===================================================================

class discover : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:udp_msg.discover) */ {
 public:
  discover();
  virtual ~discover();

  discover(const discover& from);

  inline discover& operator=(const discover& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const discover& default_instance();

  static inline const discover* internal_default_instance() {
    return reinterpret_cast<const discover*>(
               &_discover_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(discover* other);

  // implements Message ----------------------------------------------

  inline discover* New() const PROTOBUF_FINAL { return New(NULL); }

  discover* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const discover& from);
  void MergeFrom(const discover& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(discover* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string cmd_type = 1;
  bool has_cmd_type() const;
  void clear_cmd_type();
  static const int kCmdTypeFieldNumber = 1;
  const ::std::string& cmd_type() const;
  void set_cmd_type(const ::std::string& value);
  #if LANG_CXX11
  void set_cmd_type(::std::string&& value);
  #endif
  void set_cmd_type(const char* value);
  void set_cmd_type(const char* value, size_t size);
  ::std::string* mutable_cmd_type();
  ::std::string* release_cmd_type();
  void set_allocated_cmd_type(::std::string* cmd_type);

  // @@protoc_insertion_point(class_scope:udp_msg.discover)
 private:
  void set_has_cmd_type();
  void clear_has_cmd_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr cmd_type_;
  friend struct protobuf_udp_5fmsg_2ediscover_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// discover

// required string cmd_type = 1;
inline bool discover::has_cmd_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void discover::set_has_cmd_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void discover::clear_has_cmd_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void discover::clear_cmd_type() {
  cmd_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_cmd_type();
}
inline const ::std::string& discover::cmd_type() const {
  // @@protoc_insertion_point(field_get:udp_msg.discover.cmd_type)
  return cmd_type_.GetNoArena();
}
inline void discover::set_cmd_type(const ::std::string& value) {
  set_has_cmd_type();
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:udp_msg.discover.cmd_type)
}
#if LANG_CXX11
inline void discover::set_cmd_type(::std::string&& value) {
  set_has_cmd_type();
  cmd_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:udp_msg.discover.cmd_type)
}
#endif
inline void discover::set_cmd_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_cmd_type();
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:udp_msg.discover.cmd_type)
}
inline void discover::set_cmd_type(const char* value, size_t size) {
  set_has_cmd_type();
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:udp_msg.discover.cmd_type)
}
inline ::std::string* discover::mutable_cmd_type() {
  set_has_cmd_type();
  // @@protoc_insertion_point(field_mutable:udp_msg.discover.cmd_type)
  return cmd_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* discover::release_cmd_type() {
  // @@protoc_insertion_point(field_release:udp_msg.discover.cmd_type)
  clear_has_cmd_type();
  return cmd_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void discover::set_allocated_cmd_type(::std::string* cmd_type) {
  if (cmd_type != NULL) {
    set_has_cmd_type();
  } else {
    clear_has_cmd_type();
  }
  cmd_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cmd_type);
  // @@protoc_insertion_point(field_set_allocated:udp_msg.discover.cmd_type)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace udp_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_udp_5fmsg_2ediscover_2eproto__INCLUDED
