// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: udp_msg.discover.proto

#ifndef PROTOBUF_udp_5fmsg_2ediscover_2eproto__INCLUDED
#define PROTOBUF_udp_5fmsg_2ediscover_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_udp_5fmsg_2ediscover_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsdiscoverImpl();
void InitDefaultsdiscover();
inline void InitDefaults() {
  InitDefaultsdiscover();
}
}  // namespace protobuf_udp_5fmsg_2ediscover_2eproto
namespace udp_msg {
class discover;
class discoverDefaultTypeInternal;
extern discoverDefaultTypeInternal _discover_default_instance_;
}  // namespace udp_msg
namespace udp_msg {

// ===================================================================

class discover : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:udp_msg.discover) */ {
 public:
  discover();
  virtual ~discover();

  discover(const discover& from);

  inline discover& operator=(const discover& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  discover(discover&& from) noexcept
    : discover() {
    *this = ::std::move(from);
  }

  inline discover& operator=(discover&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const discover& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const discover* internal_default_instance() {
    return reinterpret_cast<const discover*>(
               &_discover_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(discover* other);
  friend void swap(discover& a, discover& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline discover* New() const PROTOBUF_FINAL { return New(NULL); }

  discover* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const discover& from);
  void MergeFrom(const discover& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(discover* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string cmd_type = 1;
  void clear_cmd_type();
  static const int kCmdTypeFieldNumber = 1;
  const ::std::string& cmd_type() const;
  void set_cmd_type(const ::std::string& value);
  #if LANG_CXX11
  void set_cmd_type(::std::string&& value);
  #endif
  void set_cmd_type(const char* value);
  void set_cmd_type(const char* value, size_t size);
  ::std::string* mutable_cmd_type();
  ::std::string* release_cmd_type();
  void set_allocated_cmd_type(::std::string* cmd_type);

  // string server_ip = 2;
  void clear_server_ip();
  static const int kServerIpFieldNumber = 2;
  const ::std::string& server_ip() const;
  void set_server_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_server_ip(::std::string&& value);
  #endif
  void set_server_ip(const char* value);
  void set_server_ip(const char* value, size_t size);
  ::std::string* mutable_server_ip();
  ::std::string* release_server_ip();
  void set_allocated_server_ip(::std::string* server_ip);

  // int32 server_port = 3;
  void clear_server_port();
  static const int kServerPortFieldNumber = 3;
  ::google::protobuf::int32 server_port() const;
  void set_server_port(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:udp_msg.discover)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr cmd_type_;
  ::google::protobuf::internal::ArenaStringPtr server_ip_;
  ::google::protobuf::int32 server_port_;
  mutable int _cached_size_;
  friend struct ::protobuf_udp_5fmsg_2ediscover_2eproto::TableStruct;
  friend void ::protobuf_udp_5fmsg_2ediscover_2eproto::InitDefaultsdiscoverImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// discover

// string cmd_type = 1;
inline void discover::clear_cmd_type() {
  cmd_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& discover::cmd_type() const {
  // @@protoc_insertion_point(field_get:udp_msg.discover.cmd_type)
  return cmd_type_.GetNoArena();
}
inline void discover::set_cmd_type(const ::std::string& value) {
  
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:udp_msg.discover.cmd_type)
}
#if LANG_CXX11
inline void discover::set_cmd_type(::std::string&& value) {
  
  cmd_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:udp_msg.discover.cmd_type)
}
#endif
inline void discover::set_cmd_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:udp_msg.discover.cmd_type)
}
inline void discover::set_cmd_type(const char* value, size_t size) {
  
  cmd_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:udp_msg.discover.cmd_type)
}
inline ::std::string* discover::mutable_cmd_type() {
  
  // @@protoc_insertion_point(field_mutable:udp_msg.discover.cmd_type)
  return cmd_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* discover::release_cmd_type() {
  // @@protoc_insertion_point(field_release:udp_msg.discover.cmd_type)
  
  return cmd_type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void discover::set_allocated_cmd_type(::std::string* cmd_type) {
  if (cmd_type != NULL) {
    
  } else {
    
  }
  cmd_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), cmd_type);
  // @@protoc_insertion_point(field_set_allocated:udp_msg.discover.cmd_type)
}

// string server_ip = 2;
inline void discover::clear_server_ip() {
  server_ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& discover::server_ip() const {
  // @@protoc_insertion_point(field_get:udp_msg.discover.server_ip)
  return server_ip_.GetNoArena();
}
inline void discover::set_server_ip(const ::std::string& value) {
  
  server_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:udp_msg.discover.server_ip)
}
#if LANG_CXX11
inline void discover::set_server_ip(::std::string&& value) {
  
  server_ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:udp_msg.discover.server_ip)
}
#endif
inline void discover::set_server_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  server_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:udp_msg.discover.server_ip)
}
inline void discover::set_server_ip(const char* value, size_t size) {
  
  server_ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:udp_msg.discover.server_ip)
}
inline ::std::string* discover::mutable_server_ip() {
  
  // @@protoc_insertion_point(field_mutable:udp_msg.discover.server_ip)
  return server_ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* discover::release_server_ip() {
  // @@protoc_insertion_point(field_release:udp_msg.discover.server_ip)
  
  return server_ip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void discover::set_allocated_server_ip(::std::string* server_ip) {
  if (server_ip != NULL) {
    
  } else {
    
  }
  server_ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), server_ip);
  // @@protoc_insertion_point(field_set_allocated:udp_msg.discover.server_ip)
}

// int32 server_port = 3;
inline void discover::clear_server_port() {
  server_port_ = 0;
}
inline ::google::protobuf::int32 discover::server_port() const {
  // @@protoc_insertion_point(field_get:udp_msg.discover.server_port)
  return server_port_;
}
inline void discover::set_server_port(::google::protobuf::int32 value) {
  
  server_port_ = value;
  // @@protoc_insertion_point(field_set:udp_msg.discover.server_port)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace udp_msg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_udp_5fmsg_2ediscover_2eproto__INCLUDED
